logging:
  level:
    org:
      hibernate: INFO
      springframework:
        web: DEBUG
    root: ALL
    
cognito:
  url: ${COGNITO_URL}
  key: ${COGNITO_KEY}
    
spring:
  profiles:
    active: ${DEPLOYMENT_STAGE}
  application:
    name: user-service

  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: NEVER
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA}
    show-sql: false
    
---
spring:
  profiles: dev    

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8888}/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    
---
spring:
  profiles: prod

server:
  port: 5000
  
eureka:
  client:
    enabled: false
    
ribbon:
  eureka: 
    enabled: false
    
user-service:
  ribbon:
    listOfServers: ${GATEWAY_URL}
    
